### PR TITLE
reworked to only reflect the changes in CardDAV owncloud, replace original pull request

### PR DESCRIPTION
**Pull request by arved**
The CardDAV Backend consits of two changed files and two new files.
the new files are: backend/carddav_oc5.php  and include/carddav_iOC5.php 
the changes were necesary to add one section in each config file:
backend/combined/config.php   and config.php
everything else can be ignored

### CODE REVIEW

**Comment by nafets227** [comment]
Hi arved and dupondje,

how to proceed? I understood our previous discussion that ist now time to merge this modified pull request (dupondje: up to you!) and afterwards I will try to Combine the new carddav_oc5 with the original carddav.

Did I get anything wrong?

**Comment by dupondje** [comment]
I still see so much things that need improvement.
Indention is wrong all over the place.
Typo's
include/carddav_iOC5.php  added, while this lib is already in PHP-Push-2
...
I really don't feel this code is ready to get merged.

The carddav code is a modified version of the original carddav code?
https://github.com/fmbiete/Z-Push-contrib/blob/master/backend/carddav/carddav.php
?
Why were there changed added to that code? It should work almost out of the box no?

**Comment by fmbiete** [comment]
Just a note, using $this->_carddav->get_all_vcards is just deadly slow... it didn't last long in my code :-P

**Comment by nafets227** [comment]
Hi dupondje,

may I ask you to have alook at PHP-Push-2-owncloud:PHP-Pus-2-oc5-unified-carddav?

I committed there the first result of merging both carddav (owncloud and Standard) that was reformatting both files to have abetter overview in Diff about real changes.
Doing this the Source Indention etc. of backend/carddav_oc5 should be much closer to your request.
Please let me know if this meets your expectation, then I can do the same for other files...

**Pull request closed without merging**
